name: Build Emscripten
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14.2
        with:
          cmake-version: '3.28.x'

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Emscripten SDK
        uses: mymindstorm/setup-emsdk@v11

      - name: Check Emscripten version
        run: emcc -v

      - name: make clang-14 the default
        run:
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-14
          100

      - name: deps fetch dependencies
        run: go run github.com/piot/deps/src/deps@main fetch

      - name: create cmake cache using emscripten (emcmake)
        run: emcmake cmake -DCMAKE_BUILD_TYPE=Debug .

      - name: build
        run: cmake --build . --clean-first
