name: build linux
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14.2
        with:
          cmake-version: '3.28.x'

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install LLVM and Clang 16
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '16.0.4'
          env: true

          - name: deps fetch dependencies
        run:
          go run github.com/piot/deps/src/deps@main fetch

      - name: create cmake cache
        run: cmake -DCMAKE_BUILD_TYPE=Debug .

      - name: build
        run: cmake --build . --clean-first -- VERBOSE=1

      - uses: actions/upload-artifact@v4
        with:
          name: Nimble Example Linux Executable
          path: |
            src/lib/nimble-minimal-example
